// Shared mock data for all design concepts

export const competition = {
  name: "Wexford FC Supporters Quiz 2026",
  description: "The lads' prediction league — bragging rights only",
  status: "active" as const,
  round: { number: 3, name: "Round 3 — May Madness" },
  totalRounds: 10,
  memberCount: 12,
};

export const leaderboard = [
  {
    rank: 1,
    name: "Davo",
    avatar: "D",
    points: 47,
    correct: 14,
    partial: 6,
    wrong: 4,
    accuracy: 58,
    streak: 5,
    streakType: "W" as const,
    movement: 0,
    form: ["W", "W", "P", "W", "W"] as const,
    funFact: "Has predicted every F1 race winner correctly this season",
  },
  {
    rank: 2,
    name: "Ger",
    avatar: "G",
    points: 44,
    correct: 13,
    partial: 5,
    wrong: 6,
    accuracy: 54,
    streak: 2,
    streakType: "W" as const,
    movement: 1,
    form: ["L", "W", "W", "P", "W"] as const,
    funFact: "Only person to back Wexford FC in every match",
  },
  {
    rank: 3,
    name: "Tommo",
    avatar: "T",
    points: 41,
    correct: 12,
    partial: 4,
    wrong: 8,
    accuracy: 50,
    streak: 1,
    streakType: "L" as const,
    movement: -1,
    form: ["W", "L", "W", "L", "L"] as const,
    funFact: "3 correct tiebreakers in a row — the luckiest man alive",
  },
  {
    rank: 4,
    name: "Sully",
    avatar: "S",
    points: 38,
    correct: 11,
    partial: 3,
    wrong: 10,
    accuracy: 46,
    streak: 0,
    streakType: "W" as const,
    movement: 2,
    form: ["L", "L", "W", "W", "P"] as const,
    funFact: "Picked 3 correct upsets nobody else saw coming",
  },
  {
    rank: 5,
    name: "Robbo",
    avatar: "R",
    points: 35,
    correct: 10,
    partial: 5,
    wrong: 9,
    accuracy: 42,
    streak: 3,
    streakType: "L" as const,
    movement: -2,
    form: ["W", "P", "L", "L", "L"] as const,
    funFact: "Hasn't picked a winner since April 12th",
  },
  {
    rank: 6,
    name: "Nidge",
    avatar: "N",
    points: 32,
    correct: 9,
    partial: 4,
    wrong: 11,
    accuracy: 38,
    streak: 1,
    streakType: "W" as const,
    movement: 0,
    form: ["L", "W", "L", "P", "W"] as const,
    funFact: "Best GAA predictor in the group — worst at everything else",
  },
];

export type LeaderboardEntry = (typeof leaderboard)[number];

export const events = [
  {
    id: "1",
    name: "Liverpool vs Arsenal",
    sport: "Soccer",
    league: "Premier League",
    startTime: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(), // 2hrs
    lockTime: new Date(Date.now() + 1.5 * 60 * 60 * 1000).toISOString(),
    status: "upcoming" as const,
    predictionTypes: ["winner", "margin"],
    funFacts: [
      "Arsenal haven't won at Anfield since 2012",
      "Liverpool have scored in 23 consecutive home matches",
      "Last meeting: Liverpool 1-1 Arsenal (Dec 2025)",
    ],
    odds: { home: 1.85, draw: 3.6, away: 4.2 },
    groupPredictions: { home: 7, draw: 3, away: 2 },
  },
  {
    id: "2",
    name: "Monaco Grand Prix",
    sport: "Formula 1",
    league: "F1 World Championship",
    startTime: new Date(Date.now() + 26 * 60 * 60 * 1000).toISOString(), // tomorrow
    lockTime: new Date(Date.now() + 25 * 60 * 60 * 1000).toISOString(),
    status: "upcoming" as const,
    predictionTypes: ["winner", "top_n"],
    funFacts: [
      "Verstappen has won 3 of the last 4 Monaco GPs",
      "Only 1 overtake happened in the 2024 race",
      "Charles Leclerc's home race — cursed since 2021",
    ],
    odds: { verstappen: 2.1, leclerc: 3.5, norris: 4.0 },
    groupPredictions: { verstappen: 5, leclerc: 4, norris: 3 },
  },
  {
    id: "3",
    name: "Wexford vs Kilkenny",
    sport: "GAA",
    league: "Leinster Hurling Championship",
    startTime: new Date(Date.now() + 50 * 60 * 60 * 1000).toISOString(),
    lockTime: new Date(Date.now() + 49 * 60 * 60 * 1000).toISOString(),
    status: "upcoming" as const,
    predictionTypes: ["winner", "margin"],
    funFacts: [
      "Wexford haven't beaten Kilkenny in championship since 2019",
      "Kilkenny are unbeaten in 8 Leinster matches",
      "Rowe has scored 2-34 in 3 games this season",
    ],
    odds: { home: 3.5, draw: 8.0, away: 1.45 },
    groupPredictions: { home: 4, draw: 1, away: 7 },
  },
  {
    id: "4",
    name: "Celtics vs Knicks — Game 5",
    sport: "NBA",
    league: "NBA Playoffs",
    startTime: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    lockTime: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    status: "resulted" as const,
    result: "Celtics 112-98",
    predictionTypes: ["winner", "margin"],
    funFacts: [
      "Tatum averaged 31.2 pts in the series",
      "Knicks haven't won at TD Garden since 2023",
    ],
    odds: { home: 1.55, away: 2.6 },
    groupPredictions: { home: 9, away: 3 },
    userPrediction: { pick: "Celtics", margin: "10-15", isCorrect: true, pointsAwarded: 8 },
  },
  {
    id: "5",
    name: "The Masters — Final Round",
    sport: "Golf",
    league: "PGA Tour Major",
    startTime: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    lockTime: new Date(Date.now() - 49 * 60 * 60 * 1000).toISOString(),
    status: "resulted" as const,
    result: "Scheffler (-14)",
    predictionTypes: ["winner", "top_n"],
    funFacts: [
      "Scheffler's 3rd green jacket — tied with Player and Faldo",
    ],
    odds: {},
    groupPredictions: {},
    userPrediction: { pick: "McIlroy", isCorrect: false, pointsAwarded: 0 },
  },
];

export type Event = (typeof events)[number];

export const stats = {
  totalPredictions: 144,
  totalEvents: 24,
  eventsResulted: 16,
  avgAccuracy: 48,
  bestStreak: { name: "Davo", count: 5 },
  closestRace: "Ger trails Davo by just 3 points",
  surpriseOfTheRound: "Nobody predicted the Wexford win over Dublin",
  roundDeadline: new Date(Date.now() + 50 * 60 * 60 * 1000).toISOString(),
};

export const sportEmoji: Record<string, string> = {
  Soccer: "\u26BD",
  "Formula 1": "\uD83C\uDFCE\uFE0F",
  GAA: "\uD83E\uDD4E",
  NBA: "\uD83C\uDFC0",
  Golf: "\u26F3",
  NFL: "\uD83C\uDFC8",
  Rugby: "\uD83C\uDFC9",
  Tennis: "\uD83C\uDFBE",
};
