// FIFA World Cup 2026 bracket adapter.
// 12 groups (A-L), 4 teams each = 48 teams total.
// R32: 16 matches (12 group winners + 12 runners-up + 8 best thirds).
// Subsequent rounds: R16 (8), QF (4), SF (2), 3rd Place (1), Final (1).
//
// All bracket structure here comes from Articles 12.6-12.11 of the FIFA WC
// 2026 Regulations (file FWC2026_regulations_EN.pdf in the repo root).

import type { BracketTemplateConfig, BracketSubmissionData } from '@/types/tournament';
import type { BracketValidationResult, OfficialBracketResults } from '@/lib/bracket/types';
import { validateBracketSubmission } from '@/lib/bracket/engine';
import {
  WC2026_BEST_THIRD_ALLOCATION,
  WC2026_BEST_THIRD_ELIGIBILITY,
  WC2026_WINNER_SLOTS,
  type Wc2026WinnerSlot,
} from '@/lib/bracket/data/wc2026-best-third-allocation';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

// 48 qualified teams (FIFA draw confirmed for WC2026 — update if draw changes).
// Groups A-L, 4 teams each.
// Official FIFA World Cup 2026 group draw (held 5 December 2025, Washington D.C.).
// Verified 2026-05-22 against NBC Sports and Sky Sports — see
// docs/WC2026-OFFICIAL-FIXTURES.md. Replaces the earlier pre-draw placeholders.
export const WC2026_GROUPS: BracketTemplateConfig['groups'] = [
  { groupId: 'A', name: 'Group A', teams: ['Mexico', 'South Korea', 'South Africa', 'Czechia'] },
  { groupId: 'B', name: 'Group B', teams: ['Canada', 'Switzerland', 'Qatar', 'Bosnia & Herzegovina'] },
  { groupId: 'C', name: 'Group C', teams: ['Brazil', 'Morocco', 'Scotland', 'Haiti'] },
  { groupId: 'D', name: 'Group D', teams: ['USA', 'Paraguay', 'Australia', 'Turkiye'] },
  { groupId: 'E', name: 'Group E', teams: ['Germany', 'Ecuador', 'Ivory Coast', 'Curacao'] },
  { groupId: 'F', name: 'Group F', teams: ['Netherlands', 'Japan', 'Tunisia', 'Sweden'] },
  { groupId: 'G', name: 'Group G', teams: ['Belgium', 'Iran', 'Egypt', 'New Zealand'] },
  { groupId: 'H', name: 'Group H', teams: ['Spain', 'Uruguay', 'Saudi Arabia', 'Cape Verde'] },
  { groupId: 'I', name: 'Group I', teams: ['France', 'Senegal', 'Norway', 'Iraq'] },
  { groupId: 'J', name: 'Group J', teams: ['Argentina', 'Austria', 'Algeria', 'Jordan'] },
  { groupId: 'K', name: 'Group K', teams: ['Portugal', 'Colombia', 'Uzbekistan', 'DR Congo'] },
  { groupId: 'L', name: 'Group L', teams: ['England', 'Croatia', 'Panama', 'Ghana'] },
];

// Knockout rounds for WC2026.
// Slot ID convention: `r32_m{n}`, `r16_m{n}`, `qf_m{n}`, `sf_m{n}`, `final`.
// Third-place match uses slot ID `third_place_match`.
export const WC2026_KNOCKOUT_ROUNDS: BracketTemplateConfig['knockoutRounds'] = [
  {
    roundKey: 'r32',
    name: 'Round of 32',
    matchCount: 16,
    slotIds: [
      'r32_m1', 'r32_m2', 'r32_m3', 'r32_m4',
      'r32_m5', 'r32_m6', 'r32_m7', 'r32_m8',
      'r32_m9', 'r32_m10', 'r32_m11', 'r32_m12',
      'r32_m13', 'r32_m14', 'r32_m15', 'r32_m16',
    ],
  },
  {
    roundKey: 'r16',
    name: 'Round of 16',
    matchCount: 8,
    slotIds: [
      'r16_m1', 'r16_m2', 'r16_m3', 'r16_m4',
      'r16_m5', 'r16_m6', 'r16_m7', 'r16_m8',
    ],
  },
  {
    roundKey: 'qf',
    name: 'Quarter-Finals',
    matchCount: 4,
    slotIds: ['qf_m1', 'qf_m2', 'qf_m3', 'qf_m4'],
  },
  {
    roundKey: 'sf',
    name: 'Semi-Finals',
    matchCount: 2,
    slotIds: ['sf_m1', 'sf_m2'],
  },
  {
    roundKey: 'final',
    name: 'Final',
    matchCount: 1,
    slotIds: ['final'],
  },
];

// ---------------------------------------------------------------------------
// Best-third allocation matrix
// ---------------------------------------------------------------------------
//
// Re-exported here for backwards compatibility with callers that imported the
// constant from this file. The authoritative copy is auto-generated by
// `scripts/extract-annex-c.ts` from Annex C of the WC 2026 Regulations PDF.
// See `src/lib/bracket/data/wc2026-best-third-allocation.ts`.
//
// Shape: key = sorted-CSV of the 8 group letters whose thirds qualified;
// value = map of winner-slot letter ('A'|'B'|'D'|'E'|'G'|'I'|'K'|'L')
// → group letter whose third they play in R32.

export const BEST_THIRD_ALLOCATION_MATRIX = WC2026_BEST_THIRD_ALLOCATION;

// ---------------------------------------------------------------------------
// R32 matchup template (Article 12.6)
// ---------------------------------------------------------------------------
//
// The 16 R32 matches in FIFA's own order, named M73-M88 in the regulations.
// Our internal slot IDs are `r32_m1` ... `r32_m16` for compatibility with
// existing bracket_data payloads; `R32_SLOT_TO_FIFA` maps to FIFA's match
// numbers for UI display.
//
// Positions are encoded as:
//   `1X`   = winner of group X
//   `2X`   = runner-up of group X
//   `3?:G` = best third from one of the groups in eligibility set G (lookup
//            into BEST_THIRD_ALLOCATION_MATRIX at scoring time)
//
// The 8 best-third slots are paired against winners A, B, D, E, G, I, K, L
// — see Article 12.6.

interface R32SlotSpec {
  /** FIFA's match number in the regulations (M73-M88). */
  fifaMatchNo: number;
  /** Home-side position token. */
  home: string;
  /** Away-side position token. */
  away: string;
}

const R32_MATCHUP_TEMPLATE: Record<string, R32SlotSpec> = {
  // M73: 2A v 2B
  r32_m1:  { fifaMatchNo: 73, home: '2A', away: '2B' },
  // M74: 1E v BestThird(ABCDF)
  r32_m2:  { fifaMatchNo: 74, home: '1E', away: '3?:E' },
  // M75: 1F v 2C
  r32_m3:  { fifaMatchNo: 75, home: '1F', away: '2C' },
  // M76: 1C v 2F
  r32_m4:  { fifaMatchNo: 76, home: '1C', away: '2F' },
  // M77: 1I v BestThird(CDFGH)
  r32_m5:  { fifaMatchNo: 77, home: '1I', away: '3?:I' },
  // M78: 2E v 2I
  r32_m6:  { fifaMatchNo: 78, home: '2E', away: '2I' },
  // M79: 1A v BestThird(CEFHI)
  r32_m7:  { fifaMatchNo: 79, home: '1A', away: '3?:A' },
  // M80: 1L v BestThird(EHIJK)
  r32_m8:  { fifaMatchNo: 80, home: '1L', away: '3?:L' },
  // M81: 1D v BestThird(BEFIJ)
  r32_m9:  { fifaMatchNo: 81, home: '1D', away: '3?:D' },
  // M82: 1G v BestThird(AEHIJ)
  r32_m10: { fifaMatchNo: 82, home: '1G', away: '3?:G' },
  // M83: 2K v 2L
  r32_m11: { fifaMatchNo: 83, home: '2K', away: '2L' },
  // M84: 1H v 2J
  r32_m12: { fifaMatchNo: 84, home: '1H', away: '2J' },
  // M85: 1B v BestThird(EFGIJ)
  r32_m13: { fifaMatchNo: 85, home: '1B', away: '3?:B' },
  // M86: 1J v 2H
  r32_m14: { fifaMatchNo: 86, home: '1J', away: '2H' },
  // M87: 1K v BestThird(DEIJL)
  r32_m15: { fifaMatchNo: 87, home: '1K', away: '3?:K' },
  // M88: 2D v 2G
  r32_m16: { fifaMatchNo: 88, home: '2D', away: '2G' },
};

/** Map our internal R32 slot IDs to FIFA's match numbers from Article 12.6. */
export const R32_SLOT_TO_FIFA_MATCH: Record<string, number> = Object.fromEntries(
  Object.entries(R32_MATCHUP_TEMPLATE).map(([slot, spec]) => [slot, spec.fifaMatchNo]),
);

// ---------------------------------------------------------------------------
// Exported functions
// ---------------------------------------------------------------------------

/**
 * Returns the full BracketTemplateConfig for FIFA World Cup 2026.
 */
export function getWC2026Template(): BracketTemplateConfig {
  return {
    groups: WC2026_GROUPS,
    knockoutRounds: WC2026_KNOCKOUT_ROUNDS,
    bestThirdConfig: {
      qualifyCount: 8,
      totalGroups: 12,
      allocationMatrix: BEST_THIRD_ALLOCATION_MATRIX,
    },
    thirdPlacePlayoff: true,
  };
}

/**
 * Given the 8 group IDs whose third-place teams qualify, returns a map of
 * winner-slot letter (one of A,B,D,E,G,I,K,L) → group letter whose third
 * occupies the R32 match against that winner.
 *
 * Uses BEST_THIRD_ALLOCATION_MATRIX (Annex C). Returns an empty object if
 * the input is not exactly 8 distinct group letters, or if the resulting
 * key is somehow not in the 495-row table (which would indicate corrupted
 * data — every C(12,8) combination is present by construction).
 */
export function allocateR32Slots(
  qualifyingThirdGroups: string[],
): Partial<Record<Wc2026WinnerSlot, string>> {
  if (qualifyingThirdGroups.length !== 8) return {};
  const unique = new Set(qualifyingThirdGroups);
  if (unique.size !== 8) return {};
  const key = [...qualifyingThirdGroups].sort().join(',');
  return BEST_THIRD_ALLOCATION_MATRIX[key] ?? {};
}

/**
 * Generate the full R32 matchup map from group rankings and best-third picks.
 * Returns a map of R32 slot ID -> { home: teamName, away: teamName }.
 *
 * The 'home' / 'away' labels here are positional only (first / second listed
 * in the official bracket slot). They carry no scheduling significance.
 *
 * Position-token grammar:
 *   "1X"   -> winner of group X
 *   "2X"   -> runner-up of group X
 *   "3?:S" -> best third paired against winner of slot S (looked up via
 *             BEST_THIRD_ALLOCATION_MATRIX with the user's bestThirdPicks)
 */
export function generateWC2026R32Matchups(
  groupRankings: Record<string, string[]>,
  bestThirdPicks: string[],
): Record<string, { home: string; away: string }> {
  const allocation = allocateR32Slots(bestThirdPicks);

  const resolve = (position: string): string => {
    if (position.startsWith('3?:')) {
      const winnerSlot = position.slice(3) as Wc2026WinnerSlot;
      const thirdGroup = allocation[winnerSlot];
      if (!thirdGroup) return '';
      return groupRankings[thirdGroup]?.[2] ?? '';
    }
    const m = position.match(/^([12])([A-L])$/);
    if (!m) return '';
    const [, position_, groupId] = m;
    const ranking = groupRankings[groupId];
    if (!ranking) return '';
    return position_ === '1' ? (ranking[0] ?? '') : (ranking[1] ?? '');
  };

  const result: Record<string, { home: string; away: string }> = {};
  for (const [slotId, spec] of Object.entries(R32_MATCHUP_TEMPLATE)) {
    result[slotId] = { home: resolve(spec.home), away: resolve(spec.away) };
  }
  return result;
}

/**
 * WC2026-specific bracket validation.
 *
 * Runs generic validation then applies WC2026 constraints:
 * - Exactly 12 groups (A-L).
 * - Each group has exactly 4 teams.
 * - Exactly 8 best-third picks.
 * - Best-third picks are valid group IDs (A-L).
 * - All R32 slots (16 matches) have picks.
 * - All subsequent knockout rounds have picks.
 * - champion and thirdPlace are present.
 */
export function validateWC2026Bracket(data: BracketSubmissionData): BracketValidationResult {
  const template = getWC2026Template();

  // Run the generic engine validation first.
  const baseResult = validateBracketSubmission(data, template);
  const errors = [...baseResult.errors];
  const warnings = [...baseResult.warnings];

  // WC2026-specific checks on top.
  const validGroupIds = new Set(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L']);
  const groupRankings = data.groupRankings ?? {};

  // Confirm exactly 12 groups are ranked.
  const rankedGroupCount = Object.keys(groupRankings).length;
  if (rankedGroupCount !== 12) {
    errors.push(`WC2026 requires rankings for all 12 groups; found ${rankedGroupCount}.`);
  }

  // Confirm all ranked groups are valid WC2026 groups.
  for (const groupId of Object.keys(groupRankings)) {
    if (!validGroupIds.has(groupId)) {
      errors.push(`WC2026: unknown group ID '${groupId}' in groupRankings.`);
    }
  }

  // Confirm exactly 8 best-third picks.
  if (data.bestThirdPicks.length !== 8) {
    // Already caught by generic validation but add WC-specific wording.
    if (!errors.some((e) => e.includes('bestThirdPicks'))) {
      errors.push(`WC2026 requires exactly 8 best-third picks; found ${data.bestThirdPicks.length}.`);
    }
  }

  // Confirm all 16 R32 slots are filled.
  const r32Slots = WC2026_KNOCKOUT_ROUNDS[0].slotIds;
  const missingR32 = r32Slots.filter((s) => !data.knockoutPicks[s]);
  if (missingR32.length > 0) {
    errors.push(`WC2026 R32: missing picks for slots: ${missingR32.join(', ')}.`);
  }

  // Confirm all R16 slots are filled.
  const r16Slots = WC2026_KNOCKOUT_ROUNDS[1].slotIds;
  const missingR16 = r16Slots.filter((s) => !data.knockoutPicks[s]);
  if (missingR16.length > 0) {
    errors.push(`WC2026 R16: missing picks for slots: ${missingR16.join(', ')}.`);
  }

  // Confirm all QF, SF, and Final slots are filled.
  for (const round of WC2026_KNOCKOUT_ROUNDS.slice(2)) {
    const missing = round.slotIds.filter((s) => !data.knockoutPicks[s]);
    if (missing.length > 0) {
      errors.push(`WC2026 ${round.name}: missing picks for slots: ${missing.join(', ')}.`);
    }
  }

  // champion is required.
  if (!data.champion) {
    if (!errors.some((e) => e.includes('champion'))) {
      errors.push('WC2026: champion is required.');
    }
  }

  // thirdPlace is required for WC2026 (thirdPlacePlayoff = true).
  if (!data.thirdPlace) {
    if (!errors.some((e) => e.includes('thirdPlace'))) {
      errors.push('WC2026: thirdPlace is required.');
    }
  }

  // Warn if the best-third combination is not in the allocation matrix.
  if (data.bestThirdPicks.length === 8) {
    const sortedKey = [...data.bestThirdPicks].sort().join(',');
    if (!BEST_THIRD_ALLOCATION_MATRIX[sortedKey]) {
      warnings.push(
        `Best-third combination '${sortedKey}' is not yet in the allocation matrix. ` +
          'R32 slot assignments for best-third teams cannot be verified until FIFA publishes the official matrix.',
      );
    }
  }

  return {
    valid: errors.length === 0,
    errors,
    warnings,
  };
}

// Re-export OfficialBracketResults for convenience when using the adapter.
export type { OfficialBracketResults };
